steps:
# Install dependencies
- name: 'python:3.12-slim'
  entrypoint: bash
  args:
  - '-c'
  - |
    pip install --upgrade pip==23.3.1
    pip install -r requirements.txt --user

# Deploy to App Engine
- name: 'python:3.12-slim'
  entrypoint: python
  args:
  - '-c'
  - |
    import os
    from google.cloud import appengine_admin_v1
    from google.cloud.appengine_admin_v1.services.versions import VersionsClient

    project_id = 'trademiddleware'  # Replace with your actual project ID
    client = VersionsClient()

    with open('app.yaml', 'r') as f:
      config = f.read()

    version = appengine_admin_v1.Version(
      runtime='python312',
      handlers=[appengine_admin_v1.UrlMap(
        url_regex='.*',
        script=appengine_admin_v1.ScriptHandler(
          script_path='main.py'
        )
      )]
    )

    request = appengine_admin_v1.CreateVersionRequest(
      parent=f'apps/{project_id}/services/default',
      version=version
    )

    operation = client.create_version(request=request)

    print(f"Deploying: {operation.metadata}")
    result = operation.result()
    print(f"Deployment finished. Version: {result.name}")

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: 'projects/trademiddleware/serviceAccounts/Cloud-build-deploy-tm@trademiddleware.iam.gserviceaccount.com'
