steps:
# Step 1: Install dependencies
- name: 'python:3.12-slim'
  entrypoint: bash
  args:
    - '-c'
    - |
      pip install --upgrade pip==23.3.1
      pip install -r requirements.txt --user
      pip install google-cloud-appengine-admin>=1.0.0

# Step 2: Deploy to App Engine
- name: 'python:3.12-slim'
  entrypoint: python
  args:
    - '-c'
    - |
      from google.cloud import appengine_admin_v1
      from google.cloud.appengine_admin_v1.services.versions import VersionsClient
      from google.cloud.appengine_admin_v1.types import CreateVersionRequest, Version, UrlMap, ScriptHandler

      project_id = 'trademiddleware'  # Replace with your actual project ID
      service_id = 'default'  # Replace with the correct service name if different

      client = VersionsClient()

      # Define the App Engine version details
      version = Version(
        runtime='python312',
        handlers=[UrlMap(
          url_regex='.*',
          script=ScriptHandler(script_path='main.py')
        )]
      )

      # Create the request object with parent and version
      request = CreateVersionRequest(
        parent=f'apps/{project_id}/services/{service_id}',  # Parent needs to be defined in request
        version=version
      )

      # Call create_version and handle the operation
      operation = client.create_version(request=request)
      print(f"Deploying... Operation metadata: {operation.metadata}")

      # Wait for the operation to complete and print result
      result = operation.result()
      print(f"Deployment finished. Version: {result.name}")

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: 'projects/trademiddleware/serviceAccounts/Cloud-build-deploy-tm@trademiddleware.iam.gserviceaccount.com'
