steps:
# Step 1: Install dependencies
- name: 'python:3.12-slim'
  entrypoint: bash
  args:
    - '-c'
    - |
      pip install --upgrade pip==23.3.1
      pip install -r requirements.txt --user
      pip install google-cloud-appengine-admin>=1.0.0

# Step 2: Deploy to App Engine using AppEngineClient
- name: 'python:3.12-slim'
  entrypoint: python
  args:
    - '-c'
    - |
      from google.cloud import appengine_admin_v1
      from google.cloud.appengine_admin_v1.services.applications import ApplicationsClient
      from google.cloud.appengine_admin_v1.types import Version, UrlMap, ScriptHandler

      project_id = 'trademiddleware'  # Replace with your actual project ID
      service_id = 'default'  # Replace with your service ID, if different
      app_id = f'apps/{project_id}'

      # Initialize the App Engine Client
      client = appengine_admin_v1.ApplicationsClient()

      # Define the App Engine version details
      version = Version(
        runtime='python312',
        handlers=[UrlMap(
          url_regex='.*',
          script=ScriptHandler(script_path='main.py')
        )]
      )

      # Try creating a new version by updating the Application
      operation = client.update_application(
          application=app_id,
          update_mask={"version": version}
      )
      
      # Wait for the operation to complete and print result
      print(f"Deploying... Operation metadata: {operation.metadata}")
      result = operation.result()
      print(f"Deployment finished. Version: {result.name}")

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: 'projects/trademiddleware/serviceAccounts/Cloud-build-deploy-tm@trademiddleware.iam.gserviceaccount.com'
